### ISSUE TITLE
Création des __cts__.xml en python

### ISSUE THREAD

**Issue by alix-tz** [Chartes-TNAH/cartulaires#11]
On peut réfléchir ensemble ici à la manière de créer deux petits scripts python (ou bien 1 seul ou on choisirait à quel niveau doit se trouver le cts) pour générer automatiquement les fichiers \_\_cts\_\_.xml.  

On va avoir besoin de : 
- une sorte de template avec la structure de base des fichiers de métadonnées
- une entrée qui donne/calcule le chemin vers l'emplacement du cts
- une entrée qui donne quelques éléments à partir desquels calculer les métadonnées ou compléter les informations de base.  

Je me permets d'utiliser la syntaxe de Jinja pour signaler les éléments pour lesquels il faudra trouver un moyen de personnaliser l'information :  

**niveau textgroup :**
``` xml
<textgroup xmlns="http://chs.harvard.edu/xmlns/cts" 
  urn="urn:cts:{{ urn_calculé }}">
	<groupname xml:lang="{{langue}}">{{nom du textgroup}}</groupname>
</textgroup> 
```

**niveau work :**  
``` xml
<work xmlns="http://chs.harvard.edu/xmlns/cts" 
    groupUrn="urn:cts:{{urn_textgroup_complété}}" 
    urn="urn:cts:{{urn_work_complété}}" xml:lang="{{langue}}">
    <title xml:lang="{{langue}}">{{titre}}</title>
    <edition workUrn="urn:cts:{{urn_edition}}" urn="urn:cts:{{urn_passage(?)}}" xml:lang="{{langue}}">
        <label xml:lang="{{langue}}">{{label}}</label>
        <description xml:lang="{{langue}}">{{description}}</description>
    </edition>
</work>
```

**Comment by MPica** [comment]
Je suis volontaire. =)

**Comment by AnneLHuet** [comment]
Moi aussi, je veux bien travailler là-dessus avec vous @alix-tz @TNAHMP

**Comment by alix-tz** [comment]
On a donc imaginé de créer un dossier tool/ dans lequel se trouverait le script python pour créer les fichiers cts. Que pensez-vous du diagramme suivant ?

![dia_cts](https://user-images.githubusercontent.com/33317799/35726196-4420b716-0804-11e8-960e-989aadd2ae81.png)

EDIT : je vous signale que dans le diagramme j'ai laissé de côté l'identification des passages (il faudra peut-être l'ajouter finalement), et la langue du "work" parce qu'on a vu que certains de nos cartulaires contiennent plusieurs langues (on pourrait faire le choix de mettre plusieurs langues, en trouvant un moyen de faire préciser par l'utilisateur combien de langues il doit y avoir).

**Comment by AnneLHuet** [comment]
C'est parfait ! Ca me semble plutôt clair ce diagramme en plus du contenu que tu as mis la dernière fois. Il ne faudra pas oublier l'encodage des fichiers \_\_cts\_\_.xml dans l'écriture.
Pour notre code, on peut déjà regarder et se familiariser avec la documentation suivante :
https://pymotw.com/2/xml/etree/ElementTree/create.html
https://docs.python.org/2/library/xml.etree.elementtree.html

EDIT : je rajoute aussi cette page http://apprendre-python.com/page-xml-python-xpath qui résume assez bien comment écrire un fichier xml simplement en python à partir du package xml

Comment peut-on se répartir le travail ? Je pense que l'étape pseudo-code est nécessaire (pour se retrouver dans la documentation et savoir exactement ce dont on a besoin), on peut peut-être définir et se partager les "grandes étapes" de celui-ci ? Qu'en pensez-vous ?

**Comment by MPica** [comment]
@alix-tz  : Ton diagramme est lumineux ! Je ne vois rien d'autre à dire.
@AnneLHuet : Merci pour la doc, je regarde ça dans la journée et je reviens vers vous pour les étapes.

**Comment by alix-tz** [comment]
Merci pour la doc Anne-Laure, je pense qu'on peut partir dans l'idée d'utiliser la bibliothèque `lxml`. Ca ne change pas la validité de mon diagramme puisque comme tu l'as fait remarquer, lxml interviendrait au moment de l'écriture du document.
Lisons la doc et voyons ensemble ensuite ce qu'on en tire !

**Comment by MPica** [comment]
J'ai regardé la doc, je suis d'accord que lxml a l'air bien adapté à ce qu'on cherche à faire.
Mais du coup, avant de commencer, est-ce qu'il ne serait pas bien d'éplucher les headers pour identifier précisément les balises contenant les infos qu'on cherche ?

**Comment by alix-tz** [comment]
A ce stade restons simple : c'est l'humain qui interagit avec le script qui va remplir les informations !

On pourra creuser plus tard une manière de pousser plus loin le programme, mais certaines informations ne sont pas contenues dans les fichiers xml, il faudra quand même les rentrer manuellement.

**Comment by MPica** [comment]
Tu as raison. Donc le début est un simple formulaire stockant les valeurs tapées par l'utilisateur, et la suite une écriture de fichier combinant lesdites valeurs avec les balises à travers la bibliothèque lxml ?

**Comment by alix-tz** [comment]
Oui, c'est ce que j'ai essayé de montrer avec le diagramme : l'utilisateur a une série de champs à remplir, les valeurs qu'il donne sont stockées voire recalculées (pour recomposer les urn par exemple), on lui fait valider les informations rentrées (parce que j'imagine qu'on peut faire des erreurs en remplissant les champs et qu'il vaut mieux pouvoir recommencer avant de lancer la création du fichier, plutôt que de devoir aller le supprimer dans le dossier de manière manuelle, au risque d'avoir remplacé le contenu d'un autre fichier cts (!!)). Par contre quand c'est validé, on crée le fichier cts à l'emplacement prévu, et avec lxml on génère le contenu du fichier. 

Donc pour le moment, côté interface entre le script et l'utilisateur, tout se ferait dans le terminal (comme on faisait au début de l'année avec le test d'estime de soi, par exemple).  

Si ça marche, on peut aussi pousser plus loin et lancer une application, mais vu qu'on a que 5 fichiers (peut-être 24 à terme) à créer, ça fait peut-être beaucoup de travail comparé au temps que ça prendrait de les faire manuellement, sans script python.

**Comment by alix-tz** [comment]
Enfin, c'est ce que j'ai compris/en tête. Si vous pensiez à autre chose, c'est le moment de clarifier ! ;)

**Comment by MPica** [comment]
Merci Alix, maintenant je suis sûre que j'ai bien compris ce que tu voulais dire et que je visualise notre procédé.

**Comment by alix-tz** [comment]
Voulez-vous qu'on travaille ensemble demain apr-s-midi sur le pseudo-code, voire sur le code ? Il me semble qu'on s'est donné comme échéance d'avoir fini les fichiers cts pour l'atelier de mardi.

**Comment by AnneLHuet** [comment]
Pour moi demain c'est bon !

**Comment by MPica** [comment]
C'est bon pour moi aussi.

**Comment by MPica** [comment]
Est-ce qu'on crée, au début du programme, un morceau de code qui :
* vérifie si le fichier cts existe déjà,
* demande (si tel est le cas) si on veut en créer un nouveau (qui écrasera le premier)
...?

**exists(path) → Teste si un chemin existe**


(Il faudra utiliser le module os.path.)
http://apprendre-python.com/page-gestion-fichiers-dossiers-python
https://www.developpez.net/forums/d858976/autres-langages/python-zope/general-python/rechercher-fichier/

**Comment by alix-tz** [comment]
Suite à notre séance de travail, je vous mets ici le fichier auquel on a abouti pour créer la partie "textgroup". On s'en servira pour créer le reste du code pour la partie "work", en l'adaptant. Ensuite, il nous faut retravailler la fonction "create" pour gérer l'écriture des informations à l'intérieur du fichier xml à l'aide de lxml.  

Anne-Laure a fait remarquer qu'il fallait prévoir de créer un environnement virtuel puisqu'il faut télécharger la library lxml. Il faudra donc créer de la doc sur la manière d'utiliser notre script (README.md).

**A faire :**  
- rédiger le code pour la branche "work"
- revoir la doc sur les environnements virtuels pour voir comment on implémente ici
- rédiger la partie du code avec lxml
- commencer à rédiger des éléments de documentation

----

``` python
#########################################
#       DEFINITION DES FONCTIONS        #
#########################################

def create(route):
    """
    Crée un fichier à partir d'un chemin donné en option.
    :param route : chemin entier depuis  tool/
    :type route : string
    """
    with open(route, "w") as fichier:
        fichier.write(information[1]) # à améliorer avec lxml
        # à améliorer avec lxml
    return

def formulaire_textgrp():
    """
    Génère une série de questions qui permet de récupérer des informations dans une liste que l'on retourne
    """
    code_textgrp = input("Quel est le code de textgroup ? : ")
    nom_textgrp = input("Quel est le nom du textgroup ? : ")
    lang_nom_txtgp = input("Quelle est la langue utilisée pour ce nom de textgroup ? : ")
    if len(lang_nom_txtgp) != 3 :
        print("/!\ Erreur sur le format de la langue : veuillez entrer un code à 3 lettres /!\ ")
        lang_nom_txtgp = input("Quelle est la langue utilisée pour ce nom de textgroup ? : ")

    chemin = "../data/" + code_textgrp + "/__cts__.xml"

    resultat = [chemin, code_textgrp, lang_nom_txtgp, nom_textgrp]
    return resultat

def valider(liste_resultat):
    """
    Enregistre et retourne une validation par l'utilisateur d'un ensemble de valeurs recueillies et affichées de manière lisible.
    :param liste_resultat : une liste qui contient les réponses d'un formulaire_textgrp
    :type liste_resultat : list
    """
    print("Un fichier __cts__.xml sera créé à l'emplacement suivant : ", liste_resultat[0])
    print("L'élément <groupname> aura comme attribut : @xml:lang= \"", liste_resultat[2], "\"")
    print("L'élément <groupname> contiendra le texte suivant : ", liste_resultat[3])
    valide = input("Valider ? [o/n]")
    return valide

#########################################
#           DEBUT DU SCRIPT             #
#########################################

valide = "n"

while valide != "o":
    information = formulaire_textgrp()
    valide = valider(information)

try:
    create(information[0])
    print("Félicitation, vous avez créé un fichier __cts__.xml, avec plein de trucs dedans !")
except FileNotFoundError:
    print("Création du fichier interrompue : erreur dans le calcul du chemin. \nVeuillez relancer le programme sans faire d'erreur")
```

**Comment by MPica** [comment]
Merci Alix ! Je veux bien m'occuper du code de la branche "work".

**Comment by alix-tz** [comment]
Je m'occupe de la question de l'environnement virtuel et de rassembler de la doc !

**Comment by AnneLHuet** [comment]
Merci ! Je rédigerais la partie du code avec lxml

**Comment by MPica** [comment]
Voilà une version du code python (sans lxml) pour créer le fichier __cts__.xml .
Elle fonctionne sur mon ordinateur, par contre j'ai des espaces qui viennent se greffer dans les ```urn:cts``` et qui les rendent donc inexacts, mais je ne sais pas d'où ça provient, j'ai déjà fait la chasse aux espaces.

``` python
#########################################
#       DEFINITION DES FONCTIONS        #
#########################################

def create(route):
	"""
	Crée un fichier à partir d'un chemin donné en option.
	:param route : chemin entier depuis  tool/
	:type route : string
	"""
	with open(route, "w") as fichier :
		fichier.write(information[1]) # à améliorer avec lxml
		# à améliorer avec lxml
	return

def formulaire_textgrp(): #TRAVAIL EN COURS
	"""
	Génère une série de questions qui permet de récupérer des informations dans une liste que l'on retourne
	"""
	code_namespace = input("Quel est le code du namespace ? : ")
	code_textgrp = input("Quel est le code de textgroup ? : ")
	code_work = input("Quel est le code de l'oeuvre ? : ")
	titre_work = input("Quel est le nom de l'oeuvre ? : ")
	lang_titre_work = input("Quelle est la langue utilisée pour le nom de l'oeuvre ? : ")
	label_edition = input("Quelle est la présente edition de l'oeuvre ? : ")
	lang_label_ed = input("Quelle est la langue utilisée pour nommer cette edition ? : ")
	code_edition = input("Quel est le code de l'edition ? : ")
	desc_ed = input("Comment souhaitez-vous decrire cette edition ? : ")
	lang_desc_ed = input("Quelle est la langue de votre description ? : ")
	if len(lang_titre_work) != 3 :
		print("/!\ Erreur sur le format de la langue du textgroup : veuillez entrer un code à 3 lettres /!\ ")
		lang_titre_work = input("Quelle est la langue utilisée pour ce nom de textgroup ? : ")
	if len(lang_label_ed) != 3 :
		print("/!\ Erreur sur le format de la langue du nom d'edition : veuillez entrer un code à 3 lettres /!\ ")
		lang_label_ed = input("Quelle est la langue utilisée pour nommer cette edition ? : ")
	if len(lang_desc_ed) != 3 :
		print("/!\ Erreur sur le format de la langue de la description de l'edition : veuillez entrer un code à 3 lettres /!\ ")
		lang_desc_ed = input("Quelle est la langue utilisée pour decrire cette edition ? : ")

	chemin = "../data/" + code_textgrp + "/" + code_work + "/__cts__.xml"

	resultat = [chemin, code_textgrp, code_work, lang_titre_work, titre_work, label_edition, lang_label_ed, code_edition, desc_ed, lang_desc_ed, code_namespace]
	return resultat

def valider(liste_resultat):
	"""
	Enregistre et retourne une validation par l'utilisateur d'un ensemble de valeurs recueillies et affichées de manière lisible.
	:param liste_resultat : une liste qui contient les réponses d'un formulaire_textgrp
	:type liste_resultat : list
	"""
	print("Un fichier __cts__.xml sera créé à l'emplacement suivant : ",liste_resultat[0],"\"")
	print("L'élément <work> aura comme attribut : @groupUrn=\"urn:cts:", liste_resultat[10],":", liste_resultat[1],"\"")
	print("L'élément <work> aura comme attribut : @urn=\"urn:cts:",liste_resultat[10],":",liste_resultat[1],":",liste_resultat[2],"\"")
	print("L'élément <work> aura comme attribut : @xml:lang=\"",liste_resultat[3],"\"") # Est-ce forcément la même langue ?
	print("L'élément <title> contiendra le texte suivant : ",liste_resultat[4])
	print("L'élément <title> aura pour attribut : @xml:lang= \"",liste_resultat[3],"\"")
	print("L'élément <edition> contiendra le texte suivant : ",liste_resultat[5])
	print("L'élément <edition> aura pour attribut : @xml:lang= \"",liste_resultat[6], "\"")
	print("L'élément <edition> aura pour attribut : @urn=\"urn:cts:",liste_resultat[10],":",liste_resultat[1],":",liste_resultat[2],":",liste_resultat[5],"\"")
	print("L'élément <description> contiendra le texte suivant : ", liste_resultat[8])
	print("L'élément <description> aura pour attribut : @xml:lang= \"", liste_resultat[9], "\"")
	valide = input("Valider ? [o/n]")
	return valide

#########################################
#           DEBUT DU SCRIPT             #
#########################################

valide = "n"

while valide != "o":
    information = formulaire_textgrp()
    valide = valider(information)

try:
    create(information[0])
    print("Félicitation, vous avez créé un fichier __cts__.xml, avec plein de trucs dedans !")
except FileNotFoundError:
    print("Création du fichier interrompue : erreur dans le calcul du chemin. \nVeuillez relancer le programme sans faire d'erreur")
```

PS : dans le premier, nous avions omis le début de l'urn du textgroup qui devrait, je pense, donner ça :
``` python
print("L'élément <work> aura comme attribut : @groupUrn=\"urn:cts:", liste_resultat[10],":", liste_resultat[1],"\"")
```

**Comment by alix-tz** [comment]
@TNAHMP @AnneLHuet je prépare une pull request avec le fichier python où : 
- j'ai combiné le morceau de code de Morgane et celui que nous avons préparé ensemble
- j'ai ajouté des commentaires pour mieux documenter le texte et les fonctions (il manquait des éléments sur les `return`)
- j'ai corrigé quelques éléments dans les deux codes, à savoir : 
   - `ligne 7` : j'ai ajouté une constante `CODE_NAMESPACE` pour prendre en compte la remarque de Morgane. *C'est une valeur qui ne va pas changer donc autant ne pas la demander dans le formulaire, mais comme quelqu'un pourrait vouloir l'adapter à un autre projet je l'ai laissé comme une variable.*
   - `ligne 86` : j'ai ajouté la validation de l'attribut de `<textgroup>` pour prendre en compte la remarque de Morgane.
   - `ligne 48` : j'ai ajouté une variable `lang_work` puisque, comme Morgane se le demandait, la langue du titre de l'oeuvre et la langue de l'oeuvre ne sont pas forcément identiques
   - j'ai modifié les tests `if`en `while` sinon en cas d'erreur répétée, on perdait la vérification, et j'ai ajouté quelques tests du même type sur certains éléments
   - j'ai utilisé une concaténation plutôt que les `,` pour régler le problème soulevé par Morgane : les espaces intempestifs
- j'ai rédigé la partie "exécution" de manière à inclure le choix de la branche. 

Il est temps de mettre le script dans le repository pour qu'on puisse suivre les modifications qui y sont apportées, notamment l'ajout de la partie lxml.

**Comment by alix-tz** [comment]
Après correction des quelques éléments de la branche "work" (cf. #23 ), si possible avant la fin du week-end, il faudrait créer les fichiers cts. L'une de vous deux veut s'en charger ?

**Comment by MPica** [comment]
Pardon, pardon, je m'en occupe (c'est presque fini).
