### ISSUE TITLE
L'utilisation du wiki pour les notes de réunions et les ressources utiles

### ISSUE THREAD

**Issue by AnneLHuet** [Chartes-TNAH/cartulaires#12]
Comme on s'est posé la question de partager les notes prises durant les réunions : 
Qu'en pensez-vous si nous les publions sur le wiki ? @TNAHMP @eglantinecharmetant 
On pourrait également y rassembler les liens / références utiles que l'on trouve ?

**Comment by eglantinecharmetant** [comment]
Oui bonne idée!

**Comment by MPica** [comment]
Oui, c'est une bonne idée !

**Comment by alix-tz** [comment]
Je suis d'accord pour mettre dans le wiki les liens utiles à la réalisation du projet, par contre je ne suis pas d'accord pour y mettre les comptes-rendus de réunion.  
Quand on se voit, c'est pour prendre des décisions ensemble sur la manière de procéder à une tâche (en général la tâche en question a une issue dédiée), ou bien pour résoudre un problème/une question (qui a aussi une issue dédiée). C'est donc à nous de répondre à nos différentes issues pendant nos réunions, quitte à faire un compte-rendu de réunion dans l'issue concernée quand la réunion a porté sur une issue en particulier.  
Les issues nous permettent de garder la chronologie de nos décisions par rapport à nos problèmes/hésitations. Ce n'est pas le cas du wiki. Je ne pense pas que ce soit judicieux d'avoir à faire des aller-retours entre les issues et le wiki pour voir quelle décision on a pris sur tel ou tel point ; et ce n'est pas non plus judicieux d'avoir un doublon entre le wiki et les issues sur ces décisions.

**Comment by AnneLHuet** [comment]
Je suis plutôt d'accord avec toi @alix-tz, je ne trouve pas ça particuliérement nécessaire, mais il me semblait que certains d'entre nous voulaient partager les notes de réunion (notamment les premières que j'ai prises, et celles de Morgane et Eglantine), sans que cela ne remplace pour autant les issues. Il ne s'agit pas forcément de faire des aller-retour entre les issues et les notes. Mais quitte à prendre des notes autant qu'elles soient partager ? Je pensais aussi aux notes prises pendant les prochains ateliers, étant donné que les questions générales que se posent les autres groupes peuvent nous être utiles pour la suite du projet.

**Comment by alix-tz** [comment]
Dans ce cas, je vois pourquoi vous voulez utiliser un wiki. Mais, à mon avis, ça doit rester pour les informations générales...

**Comment by lduflos** [comment]
Pour avoir une trace, peut-être que nous pouvons continuer à les publier dans la conversation de la team, comme nous faisions au début ?

**Comment by AnneLHuet** [comment]
@lduflos oui je pense qu'il faudrait se mettre d'accord sur où cela a sa place, et les rassembler ( parce que du coup on en a dans la conversation du début et dans certaines des issues + les notes de l'atelier qui n'ont pas été mises sur git). Ce serait peut-être mieux qu'on sache exactement où les trouver si un jour on se pose la question ?

**Comment by MPica** [comment]
Je suis d'accord pour les conversations, c'est effectivement une meilleure idée que le Wiki.
