### ISSUE TITLE
Le contenu des fichiers __cts__.xml

### ISSUE THREAD

**Issue by AnneLHuet** [Chartes-TNAH/cartulaires#14]
@PonteIneptique l'attribut `xml:lang=""` contenu dans les fichiers \_\_cts\_\_.xml du work dans les éléments `<edition>` et `<work>` est-il obligatoire ? Si oui, comment le définir pour notre corpus qui présente plusieurs langues ? Peut-on mettre plusieurs attributs `xml:lang=""` pour un seul élément ?

**Comment by PonteIneptique** [comment]
Vous pouvez utiliser "mul" pour multiple
