### ISSUE TITLE
Modification de teiHeader.rng pour ajouter l'élément RefsDecl

### ISSUE THREAD

**Issue by alix-tz** [Chartes-TNAH/cartulaires#29]
Pour rebondir sur l'issue #17.  
Avec @lduflos, nous proposons d'ajouter ce morceau de code dans le schéma du teiHeader (`schema/teiHeader.rng`) afin qu'il accepte l'élément `refsDecl` dans le fichier xml.  

``` xml
      <optional>
        <element name="refsDecl">
          <attribute name="n">
            <text/>
          </attribute>
          <oneOrMore>
            <element name="cRefPattern">
              <attribute name="n">
                <text/>
              </attribute>
              <attribute name="matchPattern">
                <text/>
              </attribute>
              <attribute name="replacementPattern">
                <text/>
              </attribute>
              <element name="p">
                <text/>
              </element>
            </element>
          </oneOrMore>
        </element>
      </optional>
```

Après un premier test dans Oxygen, cela semble convenir. @architexte , pourriez-vous relire ce morceau de schéma et nous signaler des erreurs que nous n'aurions pas vues ?

**Comment by lduflos** [comment]
Pour plus de clarté, voici le visuel de la section de notre arbre (`<encoding>`)
![capture du 2018-02-13 18-21-15](https://user-images.githubusercontent.com/33370304/36164057-7a2236ec-10eb-11e8-8f18-f70cd073b11d.png)

**Comment by alix-tz** [comment]
vu avec @eglantinecharmetant.

---
Après avoir vu @architexte , et grâce à son aide, nous avons revu les fichiers du dossier `schema/`.  
Nous avons désormais un fichier `cts.rng` à part, et dans `teiHeader.rng` un renvoi vers ce modèle.  

Après la PR qui va suivre, nous pourrons donc ajouter la déclaration des passages. 

---
*Remarque* : on pourrait améliorer le schéma rng du refsDecl en précisant les types de données acceptée, si on veut pousser plus loin, si on a le temps.

**Comment by lduflos** [comment]
Je ferme cette issue car les schemas ont été mis à jour et l'ajout des refsDecl dans les fichiers XML a été fait
