### ISSUE TITLE
README : comment préciser la version de xlmx à installer ?

### ISSUE THREAD

**Issue by MPica** [Chartes-TNAH/cartulaires#32]
En référence à la question d' @alix-tz dans la PR #26 :

> Je n'arrive pas à trouver comment préciser la version de lxml qui doit être installée :
pip install lxml fonctionne, mais comment préciser la version ? <

Il faudrait trouver comment résoudre ce problème pour pouvoir refaire une PR corrigeant ce problème dans le README.

**Comment by PonteIneptique** [comment]
`pip install lxml==VERSION`

**Comment by alix-tz** [comment]
Mystère résolu ! Il suffisait d'invoquer la bonne chimère ! ;)

**Comment by AnneLHuet** [comment]
Puisque l'on a eu réponse à notre question, et que la PR a été faite, je me permets de fermer cette issue :)
