### ISSUE TITLE
Passages et expression régulières : "forbidden characters"

### ISSUE THREAD

**Issue by alix-tz** [Chartes-TNAH/cartulaires#36]
Lorsque Léa a ajouté les sections `refsDecl` dans les fichiers xml, Travis nous a renvoyé les erreurs suivantes : 
```
Forbidden characters found:
	reg-idf.loc002.cart-enc01.xml	'XII-XIII'
	reg-idf.loc004.cart-enc01.xml	'III b', 'III t', 'LXXIII b', 'LXXV b', 'LXXXIII b', 'CVIII b', 'CXXIV b', 'CXXXIX b', 'CLIV b', 'CLVII b', 'CLXIV b', 'CLXIV t', 'CLXIV q', 'CLXXVII b', 'CLXXVIII b', 'CLXXVIII t', 'CLXXXVI b', 'CIC b', 'CIC t', 'CICII b', 'CICIV b', 'CICV b', 'CICV t', 'CICVI b'
```

A mon avis, c'est parce que les espaces et les tirets ne sont pas pris en compte dans la classe `\w`.  
Je me demande ce qu'il vaut mieux entre modifier la valeur des `@n` en intervenant directement dans les fichiers xml, ou bien modifier l'expression régulière de manière à ce qu'elle inclue les espaces ou les tirets.

**Comment by PonteIneptique** [comment]
Vous avez bien compris le problème @alix-tz mais malheureusement vous ne pouvez pas utiliser d'espace ou de tirets. Il faudra donc changer les `@n` comme vous y avez pensé.

**Comment by lduflos** [comment]
Du coup, après concertation @alix-tz tu peux modifier les 2 fichiers en supprimant les espaces pour le 004 (ex : IIIb) et en ajoutant "et" pour le 002 (ex : XIIetXIII)

**Comment by lduflos** [comment]
Je ferme cette issue car pb résolu
