### ISSUE TITLE
Problème d'indentation ? (programme de création des fichiers cts, partie textgroup)

### ISSUE THREAD

**Issue by MPica** [Chartes-TNAH/cartulaires#37]
Souhaitant créer les fichiers cts, je lance le programme Python et commence par le textgroup, mais je reçois le message d'erreur suivant :

```
Traceback (most recent call last):
  File "cts_creator.py", line 215, in <module>
    create_cts_textgrp(information)
  File "cts_creator.py", line 132, in create_cts_textgrp
    urn_calcul = 'urn:cts:' + ':' + liste_information[4] + ':' + liste_information[1]
IndexError: list index out of range
```

J'ai peur qu'il ne s'agisse, comme avant, d'un problème d'indentation à cause des changements d'éditeur qui ne font pas exactement pareil (Anne-Laure et moi avons dû reprendre toute l'indentation de la partie work pour être sûres que tout était bon avant la dernière PR #28 .)

**Comment by alix-tz** [comment]
As-tu regardé d'abord d'où venait le problème d'indexation ? La liste utilisée n'a pas l'air de contenir plus de 4 items.

**Comment by alix-tz** [comment]
Je me demande si ce n'est pas tout simplement dû au fait que vous avez laissé traîner ce `liste_information[4]` quand vous avez enlevé le "CODE_NAMESPACE" de la liste.  
La liste_information ne contient que 4 items quand il s'agit d'un `textgrp` ; j'en déduis que ce `liste_information[4]` contenait "CODE_NAMESPACE".  

Comme je n'étais pas avec vous, je vous laisse confirmer cela, mais c'est ce qui me semble ressortir de la lecture du code et de l'erreur donnée par python ! :)

**Comment by AnneLHuet** [comment]
@TNAHMP et @alix-tz c'est bien ça, nous avons oublié cette partie en reprenant le code. Du coup il faut juste remplacer `liste_information[4]` par `CODE_NAMESPACE` dans `def create_cts_textgrp()` et normalement cela devrait fonctionner.

**Comment by MPica** [comment]
Merci les filles d'avoir regardé ! Je n'y voyais pas clair et j'avais besoin d'un œil extérieur. =)

**Comment by AnneLHuet** [comment]
C'est normal ! Je ferme cette issue du coup :)
