### ISSUE TITLE
Ajout des fichiers __cts__.xml à compléter

### ISSUE THREAD

**Issue by AnneLHuet** [Chartes-TNAH/cartulaires#43]
Je propose d'ajouter les fichiers \_\_cts\_\_.xml pour le textgroup et le work avec cts_creator.py, il ne restera qu'à compléter les métadonnées

**Comment by lduflos** [comment]
Merci Anne-Laure, par contre je vois que vous avez mis pour la balise `<work>` : `xml:lang="mul"`. Normalement, on ne va pas la toucher mais hier j'ai mis "fre" du coup il faut faire attention si jamais vous faites un copier-coller
