### ISSUE TITLE
Compléter fichier __cts__.xml pour loc004

### ISSUE THREAD

**Issue by AnneLHuet** [Chartes-TNAH/cartulaires#45]
@alix-tz, j'ouvre cette issue pour qu'on puisse voir ensemble le contenu des  fichiers cts pour Saint-Leu d'Esserent (loc004)

**Comment by alix-tz** [comment]
C'est noté !

**Comment by lduflos** [comment]
#49 Attention : les urn ont été changés pour faire un test en `urn:cts:frCart`, il va falloir qu'on harmonise soit qu'on rétablisse comme c'était avant `urn:cts:FrCart`

**Comment by AnneLHuet** [comment]
@lduflos merci beaucoup ! Nous les avons modifiés :)

**Comment by alix-tz** [comment]
Comme le problème est réglé et que la modification est terminée, je ferme l'issue.
