### ISSUE TITLE
Traitement des fichiers XML

### ISSUE THREAD

**Issue by alix-tz** [Chartes-TNAH/cartulaires#51]
Je crée cette issue suite à mon message dans #46 ; mais cela vaut aussi pour #45 #42 #41 #39 ;

---

Vendredi avec Léa, nous avons essayé de résoudre un problème lors de l'exécution des tests Travis : alors qu'on s'attendait à ce que la création des fichiers cts conduise Hooktest à retourner moins d'erreurs, rien n'a changé. Samedi avec Anne-Laure nous avons travaillé sur un autre document et rencontré le même problème. Anne-Laure m'a fait remarqué que Hooktest validait nos fichiers cts, j'en déduis donc que ce sont les fichiers XML qui posent problème.  
En relisant les guidelines Capitains, je me suis rendue compte que nous avons sauté une étape (à moins que je ne me trompe). Voici le passage en question :  

> ## TEI XML  
> ### URN Information  
> There are three recommendations :  
>    1. If the text is epidoc, the convention is to supply the URN in the following xpath : `TEI/text/body/div[@type="edition"` or `@type="translation" or @type="commentary"]/@n`  
>    2. If the text is normal TEI, the convention is to supply the URN the following xpath : `TEI/text/body/@n`  
>    3. For normal TEI, it is also possible to supply the URN as the value of an `@xml:base` attribute in the following xpath: `TEI/text/@xml:base`  
> The same node should have an `xml:lang` attribute stating the language of the text.  

---

Qu'en pensez-vous ? Pour moi cela signifie qu'il nous faudrait ajouter un élément `xml:lang` et un élément `xml:base` (contenant l'urn) dans les éléments "body" ou "text" de nos documents. Actuellement, en tout cas dans le loc003, xml:lang est déclaré dans `//text/body/div`.

**Comment by alix-tz** [comment]
Après une observation plus fine de la structure des documents, on peut viser le premier élément "text", qui contient les "group".

**Comment by lduflos** [comment]
Merci @alix-tz, il faut bien ajouter dans la balise <text> (TEI/text) les attributs :
- `xml:lang="mul"`
- `xml:base="urn:cts:frCart:reg-idf.loc003.cart-enc01"` (a adapter pour chaque fichier)

**Comment by MPica** [comment]
Merci @alix-tz  et @lduflos d'avoir résolu ce problème ! Je m'occupe des fichiers loc001 et loc002 et je fais une PR.
